tasks:
  - init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      python -m ipykernel install --user --name .venv
  - command: |
      source venv/bin/activate
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
